# Form implementation generated from reading ui file '.\interfaz.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1300, 766)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_principal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_principal.setGeometry(QtCore.QRect(0, 0, 1300, 768))
        self.frame_principal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.vista1 = QtWidgets.QFrame(parent=self.frame_principal)
        self.vista1.setGeometry(QtCore.QRect(30, 50, 300, 300))
        self.vista1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;")
        self.vista1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.vista1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.vista1.setObjectName("vista1")
        self.vista2 = QtWidgets.QFrame(parent=self.frame_principal)
        self.vista2.setGeometry(QtCore.QRect(380, 50, 300, 300))
        self.vista2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;")
        self.vista2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.vista2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.vista2.setObjectName("vista2")
        self.vista3 = QtWidgets.QFrame(parent=self.frame_principal)
        self.vista3.setGeometry(QtCore.QRect(30, 400, 300, 300))
        self.vista3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;")
        self.vista3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.vista3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.vista3.setObjectName("vista3")
        self.vista4 = QtWidgets.QFrame(parent=self.frame_principal)
        self.vista4.setGeometry(QtCore.QRect(380, 400, 300, 300))
        self.vista4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;")
        self.vista4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.vista4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.vista4.setObjectName("vista4")
        self.semaforo_man = QtWidgets.QFrame(parent=self.frame_principal)
        self.semaforo_man.setGeometry(QtCore.QRect(730, 10, 521, 361))
        self.semaforo_man.setStyleSheet("#semaforo_man {\n"
"background-color: rgb(0, 0, 0);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"")
        self.semaforo_man.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.semaforo_man.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.semaforo_man.setObjectName("semaforo_man")
        self.label = QtWidgets.QLabel(parent=self.semaforo_man)
        self.label.setGeometry(QtCore.QRect(80, 10, 341, 51))
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.semaforo_man)
        self.pushButton.setGeometry(QtCore.QRect(210, 80, 75, 75))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"\n"
"border-radius:37;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.semaforo_man)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 170, 75, 75))
        self.pushButton_2.setStyleSheet("\n"
"background-color: rgb(200, 186, 29);\n"
"\n"
"border-radius:37;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.semaforo_man)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 260, 75, 75))
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"\n"
"border-radius:37;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pesos = QtWidgets.QFrame(parent=self.frame_principal)
        self.pesos.setGeometry(QtCore.QRect(730, 390, 521, 361))
        self.pesos.setStyleSheet("#pesos {\n"
"background-color: rgb(0, 0, 0);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pesos.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pesos.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.pesos.setObjectName("pesos")
        self.label_2 = QtWidgets.QLabel(parent=self.pesos)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 401, 51))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.pesos)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.pesos)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 131, 31))
        self.label_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.pesos)
        self.label_5.setGeometry(QtCore.QRect(20, 160, 131, 31))
        self.label_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.pesos)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.label_6.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.pesos)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 131, 31))
        self.label_7.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.pesos)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 131, 31))
        self.label_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit.setGeometry(QtCore.QRect(160, 60, 191, 31))
        self.lineEdit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 110, 191, 31))
        self.lineEdit_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 160, 191, 31))
        self.lineEdit_3.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 200, 191, 31))
        self.lineEdit_4.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 250, 191, 31))
        self.lineEdit_5.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.pesos)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 300, 191, 31))
        self.lineEdit_6.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.pesos)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 170, 93, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(237, 255, 8);\n"
"selection-background-color: rgb(168, 254, 57);\n"
"border: 4px solid rgb(168, 254, 57);\n"
"border-radius: 10px;")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Semaforo manual"))
        self.label_2.setText(_translate("MainWindow", "Modificacion de pesos"))
        self.label_3.setText(_translate("MainWindow", "truck"))
        self.label_4.setText(_translate("MainWindow", "bus"))
        self.label_5.setText(_translate("MainWindow", "car"))
        self.label_6.setText(_translate("MainWindow", "motorbike"))
        self.label_7.setText(_translate("MainWindow", "bicycle"))
        self.label_8.setText(_translate("MainWindow", "person"))
        self.pushButton_4.setText(_translate("MainWindow", "Aplicar pesos"))
